# -*- coding: utf-8 -*-
"""未来 10 批（第 11–20 批）词根+单词数据，预生成、按序取用。

schema 与 build_master.py 的 B 完全一致：
  {"bid","label","roots":[{"rt","mean","hook","words":[(word,ipa,释义,拆解,例句英,例句中)]}]}
已与第 01–10 批（34 族 / 185 词）逐项去重：40 个新词根族、200 个新词，零重复。
"""
FUTURE = [
 {"bid":"b11","label":"第11批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -mob / -mot / -mov","mean":"动（move）",
    "hook":"mob → 联想「mobile 移动的」「motor 发动机（驱动力）」，核心是“动”。",
    "words":[
     ("mobile","/ˈməʊbaɪl/","adj. 移动的，可动的","mob 动 + -ile 能…的 → 能动的","Mobile phones are everywhere.","手机无处不在。"),
     ("motion","/ˈməʊʃn/","n. 运动，动议","mot 动 + -ion 名词 → 运动","The car is in motion.","汽车在运动中。"),
     ("motivate","/ˈməʊtɪveɪt/","v. 激励，激发","mot 动 + -ivate 使 → 使动起来 → 激励","Praise can motivate students.","表扬能激励学生。"),
     ("promote","/prəˈməʊt/","v. 促进，晋升","pro- 向前 + mot 动 → 向前推动 → 促进","The policy promotes growth.","该政策促进增长。"),
     ("remove","/rɪˈmuːv/","v. 移开，去除","re- 回 + mov 动 → 移走 → 去除","Remove the obstacles.","清除障碍。")]},
   {"rt":"词根 ② -sol","mean":"单独（alone）",
    "hook":"sol → 联想「solo 独奏」「sole 唯一的」，核心是“单独”。",
    "words":[
     ("sole","/səʊl/","adj. 唯一的，单独的","本词根原形 → 单独","the sole survivor","唯一的幸存者"),
     ("solo","/ˈsəʊləʊ/","n./adj. 独奏，单独的","sol 单独 + -o → 独自","a solo performance","独奏表演"),
     ("isolate","/ˈaɪsəleɪt/","v. 隔离，孤立","isol[sol] 单独 + -ate 使 → 使单独 → 隔离","isolate the patient","隔离病人"),
     ("desolate","/ˈdesələt/","adj. 荒凉的，孤独的","de- 完全 + sol 单独 + -ate → 荒无人烟","a desolate island","荒岛"),
     ("solitude","/ˈsɒlɪtjuːd/","n. 独处，孤独","sol 单独 + -itude 状态 → 独处","enjoy solitude","享受独处")]},
   {"rt":"词根 ③ -lev","mean":"轻 / 举（light / raise）",
    "hook":"lev → 联想「elevator 电梯（把人举起）」「lever 杠杆（撬起重物）」，核心是“举/轻”。",
    "words":[
     ("elevate","/ˈelɪveɪt/","v. 提升，抬高","e- 向外 + lev 举 + -ate → 举起 → 提升","elevate the standard","提高标准"),
     ("lever","/ˈliːvə/","n. 杠杆","lev 举 + -er 物 → 撬起之物","pull the lever","拉杠杆"),
     ("relieve","/rɪˈliːv/","v. 减轻，缓解","re- 再 + liev[lev] 轻 → 再变轻 → 减轻","relieve the pain","缓解疼痛"),
     ("relevant","/ˈreləvənt/","adj. 相关的","re- 回 + lev 举 + -ant → 举出来相关的","relevant information","相关信息"),
     ("levy","/ˈlevi/","v./n. 征收","lev 举 + -y → 征收（举起要求）","levy a tax","征税")]},
   {"rt":"词根 ④ -magn / -maj / -max","mean":"大（great）",
    "hook":"magn → 联想「magnify 放大」「maximum 最大」，核心是“大”。",
    "words":[
     ("magnify","/ˈmæɡnɪfaɪ/","v. 放大，夸大","magn 大 + -ify 使 → 使大 → 放大","magnify the image","放大图像"),
     ("magnitude","/ˈmæɡnɪtjuːd/","n. 巨大，量级","magn 大 + -itude 名词 → 大小","the magnitude of the problem","问题的严重性"),
     ("magnificent","/mæɡˈnɪfɪsnt/","adj. 壮丽的","magn 大 + -fic 做 + -ent → 做得宏大 → 壮丽","a magnificent view","壮丽的景色"),
     ("major","/ˈmeɪdʒə/","adj. 主要的；n. 主修","maj 大 + -or → 较大的 → 主要","a major problem","主要问题"),
     ("maximum","/ˈmæksɪməm/","n./adj. 最大（值）","max 大 + -imum → 最大","the maximum speed","最大速度")]},
 ]},

 {"bid":"b12","label":"第12批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -cert","mean":"确定（sure）",
    "hook":"cert → 联想「certain 确定的」「certificate 证书（证明）」，核心是“确定”。",
    "words":[
     ("certain","/ˈsɜːtn/","adj. 确定的，某些","cert 确定 + -ain → 确定","I am certain of it.","我对此很确定。"),
     ("certify","/ˈsɜːtɪfaɪ/","v. 证明，认证","cert 确定 + -ify 使 → 使确定 → 证明","certify the document","认证文件"),
     ("certificate","/səˈtɪfɪkət/","n. 证书","cert 确定 + -ific 做 + -ate → 证明之物","a birth certificate","出生证明"),
     ("ascertain","/ˌæsəˈteɪn/","v. 查明，确定","as- 加强 + certain[确定] → 查明","ascertain the facts","查明事实"),
     ("certitude","/ˈsɜːtɪtjuːd/","n. 确信","cert 确定 + -itude → 确信","with certitude","确信地")]},
   {"rt":"词根 ② -fac / -fact / -fect","mean":"做（make / do）",
    "hook":"fac → 联想「factory 工厂（做东西的地方）」「fact 事实（已做成的事）」，核心是“做”。",
    "words":[
     ("factor","/ˈfæktə/","n. 因素","fact 做 + -or → 起作用之物 → 因素","a key factor","关键因素"),
     ("facilitate","/fəˈsɪlɪteɪt/","v. 促进，使便利","fac 做 + -ilitate → 使易做","facilitate the process","简化流程"),
     ("manufacture","/ˌmænjuˈfæktʃə/","v./n. 制造","manu 手 + fact 做 → 手工做 → 制造","manufacture goods","制造商品"),
     ("defect","/ˈdiːfekt/","n. 缺陷","de- 否定 + fect 做 → 没做好 → 缺陷","a defect in design","设计缺陷"),
     ("efficient","/ɪˈfɪʃnt/","adj. 高效的","ef- 出 + fic 做 + -ient → 做出成效 → 高效","an efficient method","高效方法")]},
   {"rt":"词根 ③ -pel / -puls","mean":"推（push / drive）",
    "hook":"pel → 联想「propel 推进（向前推）」「pulse 脉搏（搏动）」，核心是“推”。",
    "words":[
     ("propel","/prəˈpel/","v. 推进，驱动","pro- 向前 + pel 推 → 向前推 → 推进","The engine propels the ship.","发动机推动轮船。"),
     ("compel","/kəmˈpel/","v. 强迫","com- 共同 + pel 推 → 推着去做 → 强迫","The law compels us.","法律迫使我们。"),
     ("repel","/rɪˈpel/","v. 击退，排斥","re- 回 + pel 推 → 推回去 → 击退","repel the attack","击退进攻"),
     ("impulse","/ˈɪmpʌls/","n. 冲动，脉冲","im- 进 + puls 推 → 推入 → 冲动","act on impulse","冲动行事"),
     ("compulsory","/kəmˈpʌlsəri/","adj. 强制的","com- + puls 推 + -ory → 被推着做 → 强制","compulsory education","义务教育")]},
   {"rt":"词根 ④ -sequ / -secut","mean":"跟随（follow）",
    "hook":"sequ → 联想「sequence 顺序（一个跟着一个）」「consequence 结果（随之而来）」，核心是“跟随”。",
    "words":[
     ("sequence","/ˈsiːkwəns/","n. 顺序，序列","sequ 跟 + -ence → 前后相随","in sequence","依次"),
     ("consequence","/ˈkɒnsɪkwəns/","n. 结果，后果","con- 共同 + sequ 跟 + -ence → 随之而来 → 后果","face the consequence","承担后果"),
     ("subsequent","/ˈsʌbsɪkwənt/","adj. 随后的","sub- 下 + sequ 跟 + -ent → 跟在后面 → 随后","subsequent events","随后事件"),
     ("pursue","/pəˈsjuː/","v. 追求，从事","pur- 向前 + sue[sequ] 跟 → 追随 → 追求","pursue a dream","追求梦想"),
     ("execute","/ˈeksɪkjuːt/","v. 执行，处决","ex- 出 + ecut[secut] 跟 → 跟着做完 → 执行","execute the plan","执行计划")]},
 ]},

 {"bid":"b13","label":"第13批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -gen / -gener","mean":"生（birth / produce）",
    "hook":"gen → 联想「generate 生成」「gene 基因（遗传）」，核心是“生”。",
    "words":[
     ("generate","/ˈdʒenəreɪt/","v. 产生，发电","gen 生 + -erate → 产生","generate electricity","发电"),
     ("genuine","/ˈdʒenjuɪn/","adj. 真正的","gen 生 + -uine → 天生的 → 真正","genuine leather","真皮"),
     ("genius","/ˈdʒiːniəs/","n. 天才","gen 生 + -ius → 天生的才能","a genius at math","数学天才"),
     ("generous","/ˈdʒenərəs/","adj. 慷慨的","gen 生 + -ous → 天生大方 → 慷慨","a generous donation","慷慨捐赠"),
     ("gender","/ˈdʒendə/","n. 性别","gen 生 + -der → 天生类别 → 性别","gender equality","性别平等")]},
   {"rt":"词根 ② -solv / -solut","mean":"解开（loosen / solve）",
    "hook":"solv → 联想「solve 解决（解开问题）」「solution 解决方案」，核心是“解开”。",
    "words":[
     ("solve","/sɒlv/","v. 解决","本词根原形 → 解开","solve the problem","解决问题"),
     ("solution","/səˈluːʃn/","n. 解决方案","solut 解开 + -ion → 解开的办法","find a solution","找到解决办法"),
     ("resolve","/rɪˈzɒlv/","v. 解决，决心","re- 再 + solv 解 → 彻底解开 → 解决","resolve the conflict","化解冲突"),
     ("dissolve","/dɪˈzɒlv/","v. 溶解，解散","dis- 分开 + solv 解 → 解散 → 溶解","Sugar dissolves in water.","糖溶于水。"),
     ("absolute","/ˈæbsəluːt/","adj. 绝对的","ab- 离开 + solut 解 → 不受约束 → 绝对","absolute power","绝对权力")]},
   {"rt":"词根 ③ -serv","mean":"保持 / 服务（keep / serve）",
    "hook":"serv → 联想「service 服务」「preserve 保存（预先保持）」，核心是“保持/服务”。",
    "words":[
     ("serve","/sɜːv/","v. 服务，服役","本词根原形 → 服务","serve the community","服务社区"),
     ("service","/ˈsɜːvɪs/","n. 服务","serv 服务 + -ice → 服务","customer service","客服"),
     ("preserve","/prɪˈzɜːv/","v. 保存，保护","pre- 前 + serv 保持 → 预先保持 → 保存","preserve the environment","保护环境"),
     ("reserve","/rɪˈzɜːv/","v. 预订，保留","re- 回 + serv 保持 → 留住 → 预订","reserve a table","订位"),
     ("deserve","/dɪˈzɜːv/","v. 应得","de- 完全 + serv 服务 → 值得服务 → 应得","You deserve it.","这是你应得的。")]},
   {"rt":"词根 ④ -sist","mean":"站立（stand）",
    "hook":"sist → 联想「assist 帮助（站在一旁）」「insist 坚持（站定不动）」，核心是“站立”。",
    "words":[
     ("consist","/kənˈsɪst/","v. 由…组成","con- 共同 + sist 站 → 站在一起 → 组成","consist of","由…组成"),
     ("insist","/ɪnˈsɪst/","v. 坚持","in- 向内 + sist 站 → 站定 → 坚持","He insisted on it.","他坚持此事。"),
     ("persist","/pəˈsɪst/","v. 坚持，持续","per- 贯穿 + sist 站 → 一直站 → 持续","persist in effort","坚持不懈"),
     ("resist","/rɪˈzɪst/","v. 抵抗","re- 回 + sist 站 → 站住反抗 → 抵抗","resist temptation","抵制诱惑"),
     ("assist","/əˈsɪst/","v. 协助","as- 朝向 + sist 站 → 站到旁边 → 协助","assist the teacher","协助老师")]},
 ]},

 {"bid":"b14","label":"第14批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -aud","mean":"听（hear）",
    "hook":"aud → 联想「audio 音频」「audience 听众（听的人）」，核心是“听”。",
    "words":[
     ("audio","/ˈɔːdiəʊ/","adj./n. 音频","aud 听 + -io → 声音","audio equipment","音频设备"),
     ("audience","/ˈɔːdiəns/","n. 观众，听众","aud 听 + -ience → 听的人","a large audience","大批观众"),
     ("audible","/ˈɔːdəbl/","adj. 听得见的","aud 听 + -ible 能…的 → 能听见","an audible sigh","听得见的叹息"),
     ("auditorium","/ˌɔːdɪˈtɔːriəm/","n. 礼堂，观众席","aud 听 + -orium 场所 → 听讲场所","a school auditorium","学校礼堂"),
     ("audit","/ˈɔːdɪt/","v./n. 审计，旁听","aud 听 + -it → 听查 → 审计","audit the accounts","审计账目")]},
   {"rt":"词根 ② -cred","mean":"相信（believe）",
    "hook":"cred → 联想「credit 信用（可信度）」「credible 可信的」，核心是“相信”。",
    "words":[
     ("credit","/ˈkredɪt/","n. 信用，学分","cred 信 + -it → 信用","credit card","信用卡"),
     ("credible","/ˈkredəbl/","adj. 可信的","cred 信 + -ible 能…的 → 可信","a credible witness","可信的证人"),
     ("incredible","/ɪnˈkredəbl/","adj. 难以置信的","in- 不 + cred 信 + -ible → 不可信 → 惊人","an incredible story","不可思议的故事"),
     ("credentials","/krəˈdenʃlz/","n. 资格，证书","cred 信 + -ential → 证明可信之物","professional credentials","专业资质"),
     ("creed","/kriːd/","n. 信条","cred 信 → 信奉 → 信条","a political creed","政治信条")]},
   {"rt":"词根 ③ -flu","mean":"流（flow）",
    "hook":"flu → 联想「fluent 流利的（话流出来）」「flow 流动」，核心是“流”。",
    "words":[
     ("fluent","/ˈfluːənt/","adj. 流利的","flu 流 + -ent → 流出来的 → 流利","fluent English","流利的英语"),
     ("influence","/ˈɪnfluəns/","n./v. 影响","in- 进 + flu 流 + -ence → 流入 → 影响","have influence on","对…有影响"),
     ("fluid","/ˈfluːɪd/","n. 流体；adj. 流动的","flu 流 + -id → 流动之物","body fluid","体液"),
     ("fluctuate","/ˈflʌktʃueɪt/","v. 波动","flu 流 + -ctuate → 来回流动 → 波动","Prices fluctuate.","价格波动。"),
     ("influx","/ˈɪnflʌks/","n. 涌入","in- 进 + flux[flu] 流 → 流入 → 涌入","an influx of tourists","游客涌入")]},
   {"rt":"词根 ④ -her / -hes","mean":"粘附（stick）",
    "hook":"her → 联想「adhere 粘附」「hesitate 犹豫（粘住不动）」，核心是“粘”。",
    "words":[
     ("adhere","/ədˈhɪə/","v. 粘附，遵守","ad- 朝向 + her 粘 → 粘上 → 遵守","adhere to the rules","遵守规则"),
     ("coherent","/kəʊˈhɪərənt/","adj. 连贯的","co- 共同 + her 粘 + -ent → 粘在一起 → 连贯","a coherent argument","连贯的论证"),
     ("hesitate","/ˈhezɪteɪt/","v. 犹豫","hes 粘 + -itate → 粘住 → 犹豫","Don't hesitate to ask.","别犹豫，尽管问。"),
     ("inherent","/ɪnˈhɪərənt/","adj. 固有的","in- 内 + her 粘 + -ent → 内在粘着 → 固有","inherent risk","固有风险"),
     ("cohesion","/kəʊˈhiːʒn/","n. 凝聚力","co- 共同 + hes 粘 + -ion → 粘合 → 凝聚力","social cohesion","社会凝聚力")]},
 ]},

 {"bid":"b15","label":"第15批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -manu / -mani","mean":"手（hand）",
    "hook":"manu → 联想「manual 手工的」「manufacture 制造（手工做）」，核心是“手”。",
    "words":[
     ("manual","/ˈmænjuəl/","adj. 手工的；n. 手册","manu 手 + -al → 手的","a manual task","手工活"),
     ("manipulate","/məˈnɪpjuleɪt/","v. 操纵，操作","mani 手 + pul 拉 + -ate → 用手摆弄 → 操纵","manipulate the data","操纵数据"),
     ("manage","/ˈmænɪdʒ/","v. 管理","man[manu] 手 + -age → 用手打理 → 管理","manage a team","管理团队"),
     ("manifest","/ˈmænɪfest/","v. 表明；adj. 明显的","mani 手 + fest 显现 → 用手显现 → 表明","manifest the truth","表明真相"),
     ("manner","/ˈmænə/","n. 方式，举止","man[manu] 手 + -er → 手法 → 方式","in a polite manner","礼貌地")]},
   {"rt":"词根 ② -med","mean":"中间（middle）",
    "hook":"med → 联想「medium 媒介/中间」「mediate 调解（居中）」，核心是“中间”。",
    "words":[
     ("medium","/ˈmiːdiəm/","n. 媒介；adj. 中等的","med 中间 + -ium → 中间之物","the medium of TV","电视媒介"),
     ("mediate","/ˈmiːdieɪt/","v. 调解，斡旋","med 中间 + -iate → 居中调解","mediate a dispute","调解纠纷"),
     ("immediate","/ɪˈmiːdiət/","adj. 立即的，直接的","im- 无 + med 中间 + -iate → 无中间 → 立即","an immediate reply","立即回复"),
     ("intermediate","/ˌɪntəˈmiːdiət/","adj. 中间的，中级的","inter- 之间 + med 中间 + -iate → 中间","intermediate level","中级水平"),
     ("medieval","/ˌmediˈiːvl/","adj. 中世纪的","med 中间 + -ieval 时代 → 中间时代","medieval history","中世纪史")]},
   {"rt":"词根 ③ -mem","mean":"记忆（memory）",
    "hook":"mem → 联想「memory 记忆」「memorial 纪念」，核心是“记忆”。",
    "words":[
     ("memory","/ˈmeməri/","n. 记忆","mem 记 + -ory → 记忆","a good memory","好记性"),
     ("remember","/rɪˈmembə/","v. 记得","re- 回 + mem 记 + -ber → 记回来","Remember to lock.","记得锁门。"),
     ("memorial","/məˈmɔːriəl/","n. 纪念碑；adj. 纪念的","mem 记 + -orial → 纪念","a war memorial","战争纪念碑"),
     ("commemorate","/kəˈmeməreɪt/","v. 纪念","com- 共同 + mem 记 + -orate → 共同记住 → 纪念","commemorate the event","纪念该事件"),
     ("memoir","/ˈmemwɑː/","n. 回忆录","mem 记 + -oir → 记录","write a memoir","写回忆录")]},
   {"rt":"词根 ④ -migr","mean":"迁移（wander）",
    "hook":"migr → 联想「migrate 迁徙（鸟迁飞）」「immigrant 移民（迁入者）」，核心是“迁移”。",
    "words":[
     ("migrate","/maɪˈɡreɪt/","v. 迁移，迁徙","migr 迁 + -ate → 迁移","Birds migrate south.","鸟向南迁徙。"),
     ("immigrant","/ˈɪmɪɡrənt/","n. 移民（迁入）","im- 进 + migr 迁 + -ant → 迁入者","an immigrant family","移民家庭"),
     ("emigrate","/ˈemɪɡreɪt/","v. 移居国外","e- 出 + migr 迁 + -ate → 迁出","emigrate to Canada","移民加拿大"),
     ("migrant","/ˈmaɪɡrənt/","n. 移民，候鸟","migr 迁 + -ant → 迁移者","migrant workers","农民工"),
     ("migration","/maɪˈɡreɪʃn/","n. 迁移","migr 迁 + -ation → 迁移","bird migration","鸟类迁徙")]},
 ]},

 {"bid":"b16","label":"第16批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -mon","mean":"提醒 / 展示（warn / show）",
    "hook":"mon → 联想「monitor 监控（提醒）」「monument 纪念碑（展示）」，核心是“提醒/展示”。",
    "words":[
     ("monitor","/ˈmɒnɪtə/","v./n. 监控，显示器","mon 提醒 + -itor → 提醒者 → 监控","monitor the system","监控系统"),
     ("monument","/ˈmɒnjumənt/","n. 纪念碑","mon 展示 + -ument → 展示之物","a historic monument","历史纪念碑"),
     ("demonstrate","/ˈdemənstreɪt/","v. 演示，证明","de- 完全 + mon 展示 + strate → 展示清楚","demonstrate the method","演示方法"),
     ("summon","/ˈsʌmən/","v. 召唤","sum- 下 + mon 提醒 → 叫来 → 召唤","summon a meeting","召集会议"),
     ("admonish","/ədˈmɒnɪʃ/","v. 告诫","ad- 朝向 + mon 提醒 + -ish → 提醒 → 告诫","admonish the child","告诫孩子")]},
   {"rt":"词根 ② -nat","mean":"生 / 天然（born）",
    "hook":"nat → 联想「nature 自然」「native 天生的」，核心是“生/天然”。",
    "words":[
     ("nature","/ˈneɪtʃə/","n. 自然，本性","nat 生 + -ure → 天生 → 本性/自然","protect nature","保护自然"),
     ("native","/ˈneɪtɪv/","adj. 本地的，天生的","nat 生 + -ive → 出生地","a native speaker","母语者"),
     ("nation","/ˈneɪʃn/","n. 国家，民族","nat 生 + -ion → 出生地群体 → 民族","a great nation","伟大的民族"),
     ("innate","/ɪˈneɪt/","adj. 天生的","in- 内 + nat 生 → 内在生来 → 天生","innate ability","天赋"),
     ("naive","/naɪˈiːv/","adj. 天真的","naiv[nat] 生 → 初生 → 天真","a naive question","天真的问题")]},
   {"rt":"词根 ③ -neg","mean":"否定（deny）",
    "hook":"neg → 联想「negative 否定的」「neglect 忽视（否定地对待）」，核心是“否定”。",
    "words":[
     ("negative","/ˈneɡətɪv/","adj. 否定的，消极的","neg 否定 + -ative → 否定","a negative attitude","消极态度"),
     ("neglect","/nɪˈɡlekt/","v./n. 忽视","neg 否定 + lect 选 → 不选 → 忽视","neglect one's duty","玩忽职守"),
     ("negotiate","/nɪˈɡəʊʃieɪt/","v. 谈判","neg 否定 + oti 空闲 + -ate → 商谈","negotiate a deal","洽谈交易"),
     ("negligible","/ˈneɡlɪdʒəbl/","adj. 微不足道的","neg 否定 + lig 选 + -ible → 可不选的 → 微不足道","a negligible amount","微乎其微"),
     ("negate","/nɪˈɡeɪt/","v. 否定，取消","neg 否定 + -ate → 否定","negate the effect","抵消效果")]},
   {"rt":"词根 ④ -nomin / -nomen","mean":"名（name）",
    "hook":"nomin → 联想「nominate 提名（点名）」「name 名字」，核心是“名”。",
    "words":[
     ("nominate","/ˈnɒmɪneɪt/","v. 提名，任命","nomin 名 + -ate → 点名 → 提名","nominate a candidate","提名候选人"),
     ("nominee","/ˌnɒmɪˈniː/","n. 被提名者","nomin 名 + -ee 被…者 → 被提名者","a nominee for the prize","奖项候选人"),
     ("denomination","/dɪˌnɒmɪˈneɪʃn/","n. 面额，教派","de- 下 + nomin 名 + -ation → 命名 → 面额","banknotes of various denominations","各种面额纸币"),
     ("nominal","/ˈnɒmɪnl/","adj. 名义上的","nomin 名 + -al → 名义","a nominal fee","象征性费用"),
     ("renowned","/rɪˈnaʊnd/","adj. 著名的","re- 再 + nown[nomen] 名 → 闻名","a renowned scientist","著名科学家")]},
 ]},

 {"bid":"b17","label":"第17批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -path","mean":"情感 / 病（feeling / disease）",
    "hook":"path → 联想「sympathy 同情（同感）」「pathology 病理学」，核心是“情感/病”。",
    "words":[
     ("sympathy","/ˈsɪmpəθi/","n. 同情","sym- 同 + path 情 + -y → 同感 → 同情","show sympathy","表示同情"),
     ("apathy","/ˈæpəθi/","n. 冷漠","a- 无 + path 情 + -y → 无感 → 冷漠","public apathy","公众冷漠"),
     ("empathy","/ˈempəθi/","n. 共情","em- 内 + path 情 + -y → 感同身受","feel empathy","产生共情"),
     ("pathetic","/pəˈθetɪk/","adj. 可怜的","path 情 + -etic → 引发情感的 → 可怜","a pathetic sight","凄惨景象"),
     ("pathology","/pəˈθɒlədʒi/","n. 病理学","path 病 + -ology 学 → 病理学","study pathology","研究病理学")]},
   {"rt":"词根 ② -ped","mean":"脚 / 儿童（foot / child）",
    "hook":"ped → 联想「pedal 踏板（脚踩）」「pedestrian 行人（用脚走路）」，核心是“脚”。",
    "words":[
     ("pedal","/ˈpedl/","n. 踏板","ped 脚 + -al → 脚踩之物","the brake pedal","刹车踏板"),
     ("pedestrian","/pəˈdestriən/","n. 行人","ped 脚 + -estrian → 步行者","a pedestrian street","步行街"),
     ("expedition","/ˌekspəˈdɪʃn/","n. 远征，考察","ex- 出 + ped 脚 + -ition → 走出去 → 远征","an expedition to the Arctic","北极考察"),
     ("impede","/ɪmˈpiːd/","v. 阻碍","im- 进 + ped 脚 → 绊脚 → 阻碍","impede progress","阻碍进展"),
     ("centipede","/ˈsentɪpiːd/","n. 蜈蚣","centi 百 + ped 脚 → 百脚","a centipede","蜈蚣")]},
   {"rt":"词根 ③ -phil","mean":"爱（love）",
    "hook":"phil → 联想「philosophy 哲学（爱智慧）」「bibliophile 藏书家（爱书人）」，核心是“爱”。",
    "words":[
     ("philosophy","/fəˈlɒsəfi/","n. 哲学","phil 爱 + soph 智慧 + -y → 爱智慧 → 哲学","study philosophy","研究哲学"),
     ("philanthropist","/fɪˈlænθrəpɪst/","n. 慈善家","phil 爱 + anthrop 人 + -ist → 爱人类者 → 慈善家","a generous philanthropist","慷慨的慈善家"),
     ("bibliophile","/ˈbɪbliəfaɪl/","n. 藏书家","biblio 书 + phil 爱 → 爱书人","a keen bibliophile","热忱藏书家"),
     ("philharmonic","/ˌfɪləˈmɒnɪk/","adj. 爱乐的","phil 爱 + harmonic 和声 → 爱乐","the philharmonic orchestra","爱乐乐团"),
     ("anglophile","/ˈæŋɡləfaɪl/","n. 亲英者","anglo 英国 + phil 爱 → 亲英者","an anglophile","亲英派")]},
   {"rt":"词根 ④ -phon","mean":"声音（sound）",
    "hook":"phon → 联想「phone 电话（传声）」「symphony 交响乐（同声）」，核心是“声音”。",
    "words":[
     ("telephone","/ˈtelɪfəʊn/","n. 电话","tele 远 + phon 声 → 远距离传声","answer the telephone","接电话"),
     ("symphony","/ˈsɪmfəni/","n. 交响乐","sym- 同 + phon 声 + -y → 同声","a symphony concert","交响音乐会"),
     ("microphone","/ˈmaɪkrəfəʊn/","n. 麦克风","micro 微 + phon 声 → 放大声音","speak into the microphone","对着麦克风讲话"),
     ("phonetic","/fəˈnetɪk/","adj. 语音的","phon 声 + -etic → 语音","phonetic symbols","音标"),
     ("cacophony","/kəˈkɒfəni/","n. 刺耳杂音","caco 坏 + phon 声 + -y → 杂音","a cacophony of noise","嘈杂声")]},
 ]},

 {"bid":"b18","label":"第18批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -plac","mean":"取悦 / 平静（please / calm）",
    "hook":"plac → 联想「please 使高兴」「placate 安抚」，核心是“取悦/平静”。",
    "words":[
     ("placate","/pləˈkeɪt/","v. 安抚","plac 平静 + -ate → 使平静 → 安抚","placate the crowd","安抚人群"),
     ("complacent","/kəmˈpleɪsnt/","adj. 自满的","com- 完全 + plac 满足 + -ent → 满足 → 自满","a complacent attitude","自满态度"),
     ("placebo","/pləˈsiːbəʊ/","n. 安慰剂","plac 取悦 + -ebo → 取悦之物","a placebo effect","安慰剂效应"),
     ("placid","/ˈplæsɪd/","adj. 平静的","plac 平静 + -id → 平静","a placid lake","平静的湖"),
     ("implacable","/ɪmˈplækəbl/","adj. 无法平息的","im- 不 + plac 平静 + -able → 不能平息","implacable anger","无法平息的怒火")]},
   {"rt":"词根 ② -plen / -plet","mean":"满（full）",
    "hook":"plen → 联想「plenty 大量」「complete 完成（填满）」，核心是“满”。",
    "words":[
     ("plenty","/ˈplenti/","n. 大量，充足","plen 满 + -ty → 充足","plenty of time","充足的时间"),
     ("complete","/kəmˈpliːt/","v./adj. 完成，完整的","com- 完全 + plet 满 → 填满 → 完成","complete the task","完成任务"),
     ("supplement","/ˈsʌplɪmənt/","n./v. 补充","sup- 下 + ple 满 + -ment → 补满","a vitamin supplement","维生素补充剂"),
     ("implement","/ˈɪmplɪmənt/","v. 实施","im- 进 + ple 满 + -ment → 填实 → 实施","implement the policy","实施政策"),
     ("replenish","/rɪˈplenɪʃ/","v. 补充","re- 再 + plen 满 + -ish → 再填满","replenish supplies","补充物资")]},
   {"rt":"词根 ③ -quest / -quir / -quis","mean":"求（seek / ask）",
    "hook":"quest → 联想「question 问题（求答）」「request 请求」，核心是“求/问”。",
    "words":[
     ("request","/rɪˈkwest/","v./n. 请求","re- 回 + quest 求 → 请求","request a favor","请求帮助"),
     ("acquire","/əˈkwaɪə/","v. 获得","ac- 朝向 + quir 求 → 求取 → 获得","acquire knowledge","获取知识"),
     ("inquire","/ɪnˈkwaɪə/","v. 询问","in- 内 + quir 求 → 求问 → 询问","inquire about the price","询问价格"),
     ("require","/rɪˈkwaɪə/","v. 需要，要求","re- 再 + quir 求 → 要求","The job requires skills.","这份工作需要技能。"),
     ("quest","/kwest/","n. 探索，追求","本词根原形 → 寻求","a quest for truth","对真理的追求")]},
   {"rt":"词根 ④ -viv / -vit","mean":"生命 / 活（live）",
    "hook":"viv → 联想「vivid 生动的（有生命力的）」「survive 幸存（活下来）」，核心是“活”。",
    "words":[
     ("vivid","/ˈvɪvɪd/","adj. 生动的","viv 活 + -id → 活的 → 生动","a vivid description","生动的描述"),
     ("survive","/səˈvaɪv/","v. 幸存","sur- 超过 + viv 活 → 活过来 → 幸存","survive the disaster","在灾难中幸存"),
     ("revive","/rɪˈvaɪv/","v. 复苏，复兴","re- 再 + viv 活 → 再活 → 复苏","revive the economy","振兴经济"),
     ("vital","/ˈvaɪtl/","adj. 至关重要的，生命的","vit 生命 + -al → 生命攸关 → 关键","vital importance","至关重要"),
     ("vitamin","/ˈvɪtəmɪn/","n. 维生素","vit 生命 + -amin → 维持生命之物","take vitamins","服用维生素")]},
 ]},

 {"bid":"b19","label":"第19批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -rect / -reg","mean":"直 / 规则（straight / rule）",
    "hook":"rect → 联想「correct 纠正（弄直）」「regulate 规范（制定规则）」，核心是“直/规则”。",
    "words":[
     ("correct","/kəˈrekt/","adj./v. 正确的，纠正","cor- 完全 + rect 直 → 弄直 → 纠正","the correct answer","正确答案"),
     ("direct","/dəˈrekt/","adj./v. 直接的，指导","di- 分开 + rect 直 → 径直 → 直接","direct the traffic","指挥交通"),
     ("erect","/ɪˈrekt/","v. 竖立；adj. 直立的","e- 出 + rect 直 → 竖起来","erect a building","建楼"),
     ("regulate","/ˈreɡjuleɪt/","v. 规范，调节","reg 规则 + -ulate → 定规则 → 规范","regulate the market","规范市场"),
     ("regular","/ˈreɡjələ/","adj. 规律的，定期的","reg 规则 + -ular → 按规则","regular exercise","规律锻炼")]},
   {"rt":"词根 ② -scend","mean":"爬 / 升（climb）",
    "hook":"scend → 联想「ascend 上升（往上爬）」「descend 下降（往下走）」，核心是“爬/升”。",
    "words":[
     ("ascend","/əˈsend/","v. 上升","a- 向上 + scend 爬 → 上爬","ascend the mountain","登山"),
     ("descend","/dɪˈsend/","v. 下降","de- 向下 + scend 爬 → 下走","descend the stairs","下楼梯"),
     ("transcend","/trænˈsend/","v. 超越","tran- 跨越 + scend 爬 → 爬越 → 超越","transcend the limit","超越极限"),
     ("descendant","/dɪˈsendənt/","n. 后代","de- 下 + scend 爬 + -ant → 传下去的人 → 后代","a descendant of the family","家族后代"),
     ("ascent","/əˈsent/","n. 上升，攀登","a- 向上 + scent[scend] 爬 → 上升","a steep ascent","陡峭的上坡")]},
   {"rt":"词根 ③ -sci","mean":"知道（know）",
    "hook":"sci → 联想「science 科学（知识体系）」「conscious 有意识的（知道的）」，核心是“知道”。",
    "words":[
     ("science","/ˈsaɪəns/","n. 科学","sci 知道 + -ence → 知识","modern science","现代科学"),
     ("conscious","/ˈkɒnʃəs/","adj. 有意识的","con- 共同 + sci 知道 + -ous → 知道的 → 有意识","be conscious of","意识到"),
     ("conscience","/ˈkɒnʃəns/","n. 良心","con- + sci 知道 + -ence → 内心知道 → 良心","a clear conscience","问心无愧"),
     ("omniscient","/ɒmˈnɪsiənt/","adj. 无所不知的","omni 全 + sci 知道 + -ent → 全知","an omniscient narrator","全知叙述者"),
     ("prescient","/ˈpresiənt/","adj. 有先见之明的","pre- 前 + sci 知道 + -ent → 预先知道","a prescient warning","有先见之明的警告")]},
   {"rt":"词根 ④ -sed / -sid / -sess","mean":"坐（sit）",
    "hook":"sed → 联想「session 会议（坐下来开）」「president 总统（坐在前面的人）」，核心是“坐”。",
    "words":[
     ("session","/ˈseʃn/","n. 会议，一段时间","sess 坐 + -ion → 坐下来 → 会议","a training session","培训课程"),
     ("reside","/rɪˈzaɪd/","v. 居住","re- 回 + sid 坐 → 坐下来住 → 居住","reside in the city","居住在城市"),
     ("resident","/ˈrezɪdənt/","n. 居民","re- + sid 坐 + -ent → 住下来的人","local residents","当地居民"),
     ("preside","/prɪˈzaɪd/","v. 主持","pre- 前 + sid 坐 → 坐在前面 → 主持","preside over the meeting","主持会议"),
     ("sedentary","/ˈsedntri/","adj. 久坐的","sed 坐 + -entary → 坐着的","a sedentary lifestyle","久坐的生活方式")]},
 ]},

 {"bid":"b20","label":"第20批 (待排期) · 20词","roots":[
   {"rt":"词根 ① -simil / -sembl","mean":"相似（like）",
    "hook":"simil → 联想「similar 相似的」「resemble 相像」，核心是“相似”。",
    "words":[
     ("similar","/ˈsɪmələ/","adj. 相似的","simil 相似 + -ar → 相似","similar interests","相似兴趣"),
     ("resemble","/rɪˈzembl/","v. 相像","re- 再 + sembl 相似 → 相像","He resembles his father.","他像他父亲。"),
     ("simulate","/ˈsɪmjuleɪt/","v. 模拟","simul 相似 + -ate → 仿似 → 模拟","simulate the process","模拟过程"),
     ("assemble","/əˈsembl/","v. 集合，组装","as- 朝向 + sembl 相似 → 聚到一起 → 集合","assemble the parts","组装零件"),
     ("simultaneous","/ˌsɪmlˈteɪniəs/","adj. 同时的","simul 相似 + taneous → 同一时间","simultaneous translation","同声传译")]},
   {"rt":"词根 ② -tang / -tact","mean":"接触（touch）",
    "hook":"tang → 联想「contact 接触」「tangible 可触摸的」，核心是“接触”。",
    "words":[
     ("contact","/ˈkɒntækt/","n./v. 接触，联系","con- 共同 + tact 触 → 接触","contact the manager","联系经理"),
     ("intact","/ɪnˈtækt/","adj. 完好无损的","in- 不 + tact 触 → 未被触碰 → 完好","remain intact","保持完好"),
     ("tangible","/ˈtændʒəbl/","adj. 有形的，切实的","tang 触 + -ible 能…的 → 可触摸","tangible results","切实成果"),
     ("tactile","/ˈtæktaɪl/","adj. 触觉的","tact 触 + -ile → 触觉","tactile feedback","触觉反馈"),
     ("contagious","/kənˈteɪdʒəs/","adj. 传染性的","con- 共同 + tag[tang] 触 + -ious → 接触传播","a contagious disease","传染病")]},
   {"rt":"词根 ③ -term / -termin","mean":"界限（boundary / end）",
    "hook":"term → 联想「terminal 终点（边界）」「determine 决定（划定界限）」，核心是“界限”。",
    "words":[
     ("term","/tɜːm/","n. 术语，学期，条款","本词根原形 → 界限/界定","in the long term","从长远看"),
     ("terminal","/ˈtɜːmɪnl/","n. 终点站；adj. 末期的","termin 界限 + -al → 终点","a bus terminal","公交总站"),
     ("determine","/dɪˈtɜːmɪn/","v. 决定，确定","de- 完全 + termin 界限 → 划定 → 决定","determine the result","决定结果"),
     ("terminate","/ˈtɜːmɪneɪt/","v. 终止","termin 界限 + -ate → 到终点 → 终止","terminate the contract","终止合同"),
     ("exterminate","/ɪkˈstɜːmɪneɪt/","v. 消灭","ex- 出 + termin 界限 + -ate → 逐出边界 → 消灭","exterminate pests","消灭害虫")]},
   {"rt":"词根 ④ -tort","mean":"扭（twist）",
    "hook":"tort → 联想「distort 扭曲（扭变形）」「torture 折磨（扭打）」，核心是“扭”。",
    "words":[
     ("distort","/dɪˈstɔːt/","v. 扭曲，歪曲","dis- 分开 + tort 扭 → 扭开 → 扭曲","distort the facts","歪曲事实"),
     ("torture","/ˈtɔːtʃə/","n./v. 折磨，拷问","tort 扭 + -ure → 扭打 → 折磨","ban torture","禁止酷刑"),
     ("retort","/rɪˈtɔːt/","v./n. 反驳","re- 回 + tort 扭 → 扭回去 → 反驳","a sharp retort","尖锐的反驳"),
     ("extort","/ɪkˈstɔːt/","v. 敲诈","ex- 出 + tort 扭 → 扭出来 → 敲诈","extort money","勒索钱财"),
     ("contort","/kənˈtɔːt/","v. 扭曲","con- 完全 + tort 扭 → 扭成一团","contort with pain","痛得扭曲")]},
 ]},
]
